sudo: required
dist: trusty

language: perl

before_install:
- wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
- sudo apt-get -y install software-properties-common
- sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
- sudo apt-get update

install:
# OpenResty
- sudo apt-get -y install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make build-essential
- sudo apt-get install openresty
- sudo mkdir -p /usr/local/openresty/nginx/{logs,lock,run,client_body_temp,fastcgi_temp,proxy_temp,scgi_temp,uwsgi_temp}
- sudo chmod 0777 /usr/local/openresty/nginx/logs

# Test
- cpanm --quiet --notest
  Test::Nginx
  Log::Log4perl

script:
- prove -r t
