sudo: required
dist: trusty

language: perl

before_install:
- sudo apt-get update

install:
# OpenResty
- sudo apt-get -y install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make build-essential
- wget https://openresty.org/download/openresty-1.13.6.2.tar.gz
- tar xzvf openresty-1.13.6.2.tar.gz
- cd openresty-1.13.6.2/
- ./configure
  --prefix=/usr/local/openresty
  --with-debug
  --conf-path=/usr/local/openresty/nginx/conf/nginx.conf
  --http-log-path=/usr/local/openresty/nginx/logs/access.log
  --error-log-path=/usr/local/openresty/nginx/logs/error.log
  --lock-path=/usr/local/openresty/nginx/lock/nginx.lock
  --pid-path=/usr/local/openresty/nginx/run/nginx.pid
  --http-client-body-temp-path=/usr/local/openresty/nginx/client_body_temp
  --http-fastcgi-temp-path=/usr/local/openresty/nginx/fastcgi_temp
  --http-proxy-temp-path=/usr/local/openresty/nginx/proxy_temp
  --http-scgi-temp-path=/usr/local/openresty/nginx/scgi_temp
  --http-uwsgi-temp-path=/usr/local/openresty/nginx/uwsgi_temp
- make
- sudo make install
- cd ../
- sudo mkdir -p /usr/local/openresty/nginx/{logs,lock,run,client_body_temp,fastcgi_temp,proxy_temp,scgi_temp,uwsgi_temp}
- export PATH=/usr/local/openresty/bin:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:$PATH

# LuaRocks
- wget http://luarocks.github.io/luarocks/releases/luarocks-3.0.4.tar.gz
- tar xzvf luarocks-3.0.4.tar.gz
- cd luarocks-3.0.4/
- ./configure --lua-suffix=jit --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
- sudo make bootstrap
- cd ../
- sudo luarocks install lrexlib-PCRE

# Test
- cpanm --quiet --notest
  Test::Nginx
  Log::Log4perl

script:
- prove -r t
